### ISSUE TITLE
Offense wurde falsch geschrieben

### ISSUE THREAD

**Issue by Laberbear** [SweProject2016/Backend#1]
https://github.com/SweProject2016/Backend/blob/master/src/main/java/de/hwrberlin/it2014/sweproject/database/Judgement.java#L12

Ist zwar kein Rechtschreibtest, aber je früher wir sowas korrigieren, desto besser!

**Comment by dominikh05** [comment]
http://www.dict.cc/englisch-deutsch/offence.html
vs.
http://www.dict.cc/englisch-deutsch/offense.html

Mit "c" hat das mehr einen Juristen-Vibe.
