### ISSUE TITLE
[REST-API] Möglichkeit HTTPRequests zu identifizieren

### ISSUE THREAD

**Issue by Laberbear** [SweProject2016/Backend#12]
Damit beim extrem langsamen Antworten es immer genau bekannt ist, welche Antwort zu welchem request gehört, hätte ich gerne eine Möglichkeit diese zu identifizieren.
Ich denke den ich vom Frontend dem Server gebe, und der dann zurückgeschickt wird (also der gleiche) sollte ausreichen!

Falls es dafür bessere Methoden gibt, sagt ruhig Bescheid.

**Comment by ghost** [comment]
Geht klar

**Comment by ghost** [comment]
Implementiert!
